### ISSUE TITLE
more than 1 PWS in Home-Assistant-Wundergroundpws v1.X.X?

### ISSUE THREAD

**Issue by arrikhan** [cytech/Home-Assistant-wundergroundpws#127]
After upgrading to version "Home-Assistant-Wundergroundpws v1.X.X", I can no longer configure more than one PWS. Please advise if this is still supported (as per old config).

**Comment by cpuks** [comment]
I'm facing same issue - running two PWS in two locations - only one can be used.

**Comment by shtrom** [comment]
Hum, with the refactor for v1, it is likely not supported at the moment. Maybe the config could support an array of PWS IDs, instead of one, and then the data provider could query them all at once, which I think the Weather API support.

We would likely need to address #83, too, so the entities can be distinguishable.

**Comment by tshawning** [comment]
same issue here as well.  thanks so much for considering adding support for this

**Comment by cytech** [comment]
added v2.0.1
https://github.com/cytech/Home-Assistant-wundergroundpws/tree/v2.X.X
