### ISSUE TITLE
Dev 2.x.x bug

### ISSUE THREAD

**Issue by uroh** [cytech/Home-Assistant-wundergroundpws#158]
The Dev 2.x.x version is fantastic, the errors generated when I restarted hassio disappeared.

Some glitches: 
1. When adding the station to the device, the labels are missing, so I was lucky in entering the API and the station name. 
2. By ticking the additional sensors they appear as disabled, so you need to enable them manually. 

Thanks for the work.

**Comment by cytech** [comment]
I am still working v2 so use it at your own peril.... i have not released it yet. 
what language are you using?
I only have the en.json in the config_flow translation strings.
Also, I made the decision to add the forecast sensors as disabled and make you enable the ones you wanted so that there weren't 79 unnecessary sensors showing up when added to a card.
this is noted in the install doc.

**Comment by barto64** [comment]
Hey,

Great job for this integration. Not sure if it has been already considered for this version, but ......

Would it be possible to make it HACS compliance?, in a way that installation and more importantly upgrades were automated.

Thanks.

**Comment by jmtatsch** [comment]
@barto64 #71
