### ISSUE TITLE
Error - not a valid unit for the device class ('irradiance')

### ISSUE THREAD

**Issue by AdmiralStipe** [cytech/Home-Assistant-wundergroundpws#222]
**Describe the bug**
At every restart of HA I get an error message as follows:

Entity sensor.iidrij44_solar_radiation (<class 'custom_components.wundergroundpws.sensor.WundergroundPWSSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('irradiance') it is using; expected one of ['BTU/(h⋅ft²)', 'W/m²']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/cytech/Home-Assistant-wundergroundpws/issues/

I tried deleting the configurations and the addon, completely deleting folder "/custom_components/wundergroundpws" and it's contents, did a clean reinstall, but the issue remains. Also tried customizing the unit of measurement in customize.yaml, but no success.

**To Reproduce**
1. Install the addon
2. Configure one station to read from
3. Restart HA

**Expected behavior**
No error at startup

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: Debian 11, HA Supervised installation
 - Browser : not related to browser
 - Version: HA core-2024.1.1, HA-Wundergroundwps 2.0.5

**Additional context**
 The issue is only present since installing the version 2.X last month - before I was using 0.8.3 and it showed no errors.

**Comment by norburban** [comment]
I'm getting the same one of the two stations I'm connecting to.  Perhaps it's a limitation on the particular station?

2024-01-16 11:11:41.865 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.kmolakes29_solar_radiation (<class 'custom_components.wundergroundpws.sensor.WundergroundPWSSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('irradiance') it is using; expected one of ['BTU/(h⋅ft²)', 'W/m²']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/cytech/Home-Assistant-wundergroundpws/issues/

**Comment by cytech** [comment]
if your station does not report solar radiation then:
settings-devices & services - wundergroundpws-entities search for and disable the Solar Radiation forecast sensor entity.
