### ISSUE TITLE
Home Assistant 2024.3

### ISSUE THREAD

**Issue by tacopiek** [cytech/Home-Assistant-wundergroundpws#239]
See the following log book error for the upcoming version of hine assistant os 2024.3

Logger: homeassistant.components.weather
Bron: components/weather/__init__.py:387
integratie: Weer (documentation, issues)
First occurred: 09:14:16 (1 gebeurtenissen)
Laatst gelogd: 09:14:16

wundergroundpws::WUWeather implements the `forecast` property or sets `self._attr_forecast` in a subclass of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please create a bug report at https://github.com/cytech/Home-Assistant-wundergroundpws/issues/

**Comment by cytech** [comment]
i dont know what version of wupws you are running, but you need to upgrade to the latest v2.x.x
version 1.x.x is no longer supported

**Comment by agnus777** [comment]
I'm using weather clock card and wundergorund v2 didn't expose anymore forecast on weather sensor.
This happen just after update to  core 2024.4.0
Now is running the 024.4.1 update but no changes

Core
2024.4.1
Supervisor
2024.03.1
Operating System
Frontend
20240404.1

Following screenshots of actual wundergrou d weather sensor and open meteo weather sensor which working fine in weather clock card

![Screenshot_2024-04-05-21-40-01-73_c3a231c25ed346e59462e84656a70e50](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/80893750/9e401e59-74d0-4d0d-8e46-8e5185e7b417)
![Screenshot_2024-04-05-21-40-35-26_c3a231c25ed346e59462e84656a70e50](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/80893750/ac9b7c33-1660-4be2-901d-de600f3e2dac)

Thanks for any feedback

Regards 

Alessio

**Comment by Lateadapter** [comment]
@agnus777 
I did have similar issue after upgrade from HA Core 2024.3 to 2024.4.2. "Platinum weather card" didn't work anymore, even after changing to  recommended fork [https://community.home-assistant.io/t/platinum-weather-card-support/449166/250](url)...
Also the "weather forcast" card didn't show anymore the forcast...

I solved it with (not sure, what measure finally was the root cause):
a) upgrade to latest version of Home-Assistant-wundergroundpws (from 2.0.3. to 2.0.6) by overwriting the content in custom_components directory, deleting the existend wunderground-configuration under devices/integrations, restarting HA and finally add the integration again
b) now the "weather forcast" card in addition did require a change to "forecast_type: daily" (previously it was "legacy") ... similar in "Platinum weather card"
