### ISSUE TITLE
Thunderstorms icon ?

### ISSUE THREAD

**Issue by Grey-Lancaster** [cytech/Home-Assistant-wundergroundpws#6]
I think I am missing an icon?  Anyway to figure out what it is looking for?

Also just what is the slider for?
Thanks,
Grey

![wu](https://user-images.githubusercontent.com/20055899/58880654-6ba24300-86a6-11e9-95a2-8dc747d20f0b.JPG)

**Comment by cytech** [comment]
slider is turned on in the card (it has no purpose here).
you can configure-ui, edit the card, and turn off "Show Header Toggle?"
icon is returned from the weatherground forecast json as a number in daypart-> iconCode .
there are 10 numbers there for each day (5days), daytime and nighttime.
these numbers are mapped to the icon number in the wupws_icons directory.
there could very well be inconsistencies here because I pretty much ignored the nighttime icons and  assumed a direct map to the wunderground icons in wupws_icons

**Comment by Grey-Lancaster** [comment]
Thanks,
Grey
