### ISSUE TITLE
Wunderground component improvement proposal

### ISSUE THREAD

**Issue by barto64** [cytech/Home-Assistant-wundergroundpws#79]
Hey,

Just new to your integration, it looks great, thanks for the job done. 

Could I propose you add to the sensors the attribute "state_class: measurement" ?

It allows HA to natively create statistics and graphs of the sensors out of the box. It was introduced very recently in HA.

Thanks

**Comment by cytech** [comment]
added to v1.0.2

**Comment by Jerzeek** [comment]
😅Seems to be added everywhere, but somehow my home assistant configuration still does not let me add the sensors to statistics(graphs) 
It is the first time I have been using this integration, so never installed anything before v1.0.2.
Tried with both decimal and none.
Anything I can help/upload here to fix this?

**Comment by cytech** [comment]
do  you by chance have a recorder_included.yaml file defined in config?
if so you have to include the wupws sensors in there.

**Comment by Jerzeek** [comment]
Awesome quick reply, i do not have a recorder_included.yaml file or recorder defined.

**Comment by cytech** [comment]
what version HASS?
is this what you are looking for?
or  something else..

![image](https://user-images.githubusercontent.com/7809634/208301850-a25240ef-ee07-4c20-b967-3bf263125ca9.png)

**Comment by Jerzeek** [comment]
So I can make a history graph, which you are also showing up there👆, but I cannot make a statistical graph.
If you make a new graph in lovelace, you can choose one of the following items:
![image](https://user-images.githubusercontent.com/22919620/208302377-ce11ff80-be9c-4fab-b526-fc5fd491f290.png)
I would like to choose the right one, so that I can make a graph something like this:
![image](https://user-images.githubusercontent.com/22919620/208302302-86a696e2-f1e4-4f84-8c20-ca9046662798.png)
It also makes it possible to store data for a longer time.

My version of HASS is: 
![image](https://user-images.githubusercontent.com/22919620/208302645-c8045fda-a7ba-41bf-9dd6-1cfe798d8150.png)
On a Raspberry Pi 4

**Comment by Jerzeek** [comment]
The home assistant  [dashboard page](https://www.home-assistant.io/dashboards/statistics-graph/) is linking to this article:
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by cytech** [comment]
ill look into it when i get some time

**Comment by cytech** [comment]
ok, found the issue.
this is fixed for the next wundergroundpws release v1.0,3
i have only exposed a small set of sensors (that make sense) to statistics:
uv, winddir,preciprate,windgust,windspeed,preciptotal,pressure,humidity,solarradiation,dewpt,heatindex,windchill and temp.
unfortunately the changes are based on HASS development version changes, so wundergroundpws release v1.0,3
will not be released until at least HASS v2023.1.0
thanx
